In [1]:
import tensorflow as tf
import numpy as np
import time

tf.__version__

'2.0.0'

## Simple Example (2 variables)

In [2]:
start = time.time()

tf.random.set_seed(0)

x1_data = [1, 0, 3, 0, 5]
x2_data = [0, 2, 0, 4, 0]
y_data = [1, 2, 3, 4, 5]

W1 = tf.Variable( tf.random.uniform((1,), -10, 10) )
W2 = tf.Variable( tf.random.uniform((1,), -10, 10) )
b = tf.Variable( tf.random.uniform((1,), -10, 10) )

learning_rate = 0.001

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = tf.multiply(W1, x1_data) + tf.multiply(W2, x2_data) + b
        cost = tf.reduce_mean(tf.square(tf.subtract(hypothesis, y_data)))
    
    if i%100 == 0:
        print(f'epoch :{i+1:5}  |  W1 :{W1.numpy()[0]:7.3f}  |  W2 :{W2.numpy()[0]:7.3f}  | ',
              f'b : {b.numpy()[0]:7.3f}  |  cost : {cost:7.3f}')
    
    W1_grad, W2_grad, b_grad = tape.gradient(cost, [W1, W2, b])
    W1.assign_sub( tf.multiply(learning_rate, W1_grad) )
    W2.assign_sub( tf.multiply(learning_rate, W2_grad) )
    b.assign_sub( tf.multiply(learning_rate, b_grad) )
    pass

finish = time.time()
print('>>> training time : ', finish-start)

epoch :    1  |  W1 : -4.160  |  W2 :  1.108  |  b :  -6.096  |  cost : 335.281
epoch :  101  |  W1 :  0.695  |  W2 :  1.874  |  b :  -4.437  |  cost :  18.959
epoch :  201  |  W1 :  1.724  |  W2 :  2.076  |  b :  -3.964  |  cost :   3.445
epoch :  301  |  W1 :  1.922  |  W2 :  2.118  |  b :  -3.764  |  cost :   2.525
epoch :  401  |  W1 :  1.940  |  W2 :  2.112  |  b :  -3.631  |  cost :   2.337
epoch :  501  |  W1 :  1.922  |  W2 :  2.088  |  b :  -3.516  |  cost :   2.196
epoch :  601  |  W1 :  1.896  |  W2 :  2.060  |  b :  -3.408  |  cost :   2.066
epoch :  701  |  W1 :  1.869  |  W2 :  2.030  |  b :  -3.305  |  cost :   1.944
epoch :  801  |  W1 :  1.843  |  W2 :  1.999  |  b :  -3.206  |  cost :   1.829
epoch :  901  |  W1 :  1.817  |  W2 :  1.970  |  b :  -3.109  |  cost :   1.720
epoch : 1001  |  W1 :  1.793  |  W2 :  1.941  |  b :  -3.016  |  cost :   1.618
>>> training time :  5.9153382778167725


## Simple Example (2 variables with Matrix)

In [3]:
start = time.time()

x_data = [
    [1., 0., 3., 0., 5.],
    [0., 2., 0., 4., 0.]
]
y_data = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random.uniform((1, 2), -1, 1))
b = tf.Variable(tf.random.uniform((1,), -1, 1))

learning_rate = 0.001

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(W, x_data) + b
        cost = tf.reduce_mean(tf.square(tf.subtract(hypothesis, y_data)))
        pass
    
    if i%100 == 0:
        print(f'{i+1:5} epoch  |  {W.numpy()[0][0]:7.3f}  |  {W.numpy()[0][1]:7.3f}',
              f' |  {b.numpy()[0]:7.3f}  |  cost : {cost:7.3f}')
    
    W_grad, b_grad = tape.gradient( cost, [W, b] )
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    
finish = time.time()
print('>>> training time : ', finish-start)

    1 epoch  |   -0.650  |   -0.364  |   -0.973  |  cost :  36.404
  101 epoch  |    0.701  |    0.482  |   -0.351  |  cost :   2.640
  201 epoch  |    0.971  |    0.807  |   -0.175  |  cost :   0.285
  301 epoch  |    1.019  |    0.936  |   -0.119  |  cost :   0.043
  401 epoch  |    1.025  |    0.989  |   -0.098  |  cost :   0.008
  501 epoch  |    1.024  |    1.010  |   -0.088  |  cost :   0.002
  601 epoch  |    1.022  |    1.019  |   -0.083  |  cost :   0.001
  701 epoch  |    1.021  |    1.022  |   -0.080  |  cost :   0.001
  801 epoch  |    1.020  |    1.023  |   -0.077  |  cost :   0.001
  901 epoch  |    1.020  |    1.023  |   -0.074  |  cost :   0.001
 1001 epoch  |    1.019  |    1.022  |   -0.072  |  cost :   0.001
>>> training time :  6.2733588218688965


## Hypothesis without b

In [4]:
start = time.time()

x_data = [
    [1., 1., 1., 1., 1.],
    [1., 0., 3., 0., 5.],
    [0., 2., 0., 4., 0.]
]
y_data = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random.uniform((1,3), -1, 1))

learning_rate = 0.001
optimizer = tf.keras.optimizers.SGD(learning_rate)

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(W, x_data)
        cost = tf.reduce_mean(tf.square(tf.subtract(hypothesis, y_data)))
        pass
    
    if i%100 == 0:
        print(f'{i+1:5} epoch  |  {W.numpy()[0][0]:7.3f}  |  {W.numpy()[0][1]:7.3f} ',
              f'|  {W.numpy()[0][2]:7.3f}  |  cost : {cost.numpy():7.3f}')
    
    grads = tape.gradient( cost, [W] )
    optimizer.apply_gradients(grads_and_vars = zip(grads, [W]))

finish = time.time()
print('>>> training time : ', finish-start)

    1 epoch  |   -0.205  |    0.332  |   -0.698  |  cost :  16.020
  101 epoch  |    0.198  |    0.822  |    0.230  |  cost :   2.141
  201 epoch  |    0.322  |    0.901  |    0.609  |  cost :   0.367
  301 epoch  |    0.359  |    0.908  |    0.767  |  cost :   0.085
  401 epoch  |    0.366  |    0.907  |    0.835  |  cost :   0.036
  501 epoch  |    0.362  |    0.906  |    0.866  |  cost :   0.026
  601 epoch  |    0.354  |    0.908  |    0.881  |  cost :   0.023
  701 epoch  |    0.345  |    0.910  |    0.889  |  cost :   0.021
  801 epoch  |    0.335  |    0.912  |    0.894  |  cost :   0.020
  901 epoch  |    0.325  |    0.915  |    0.898  |  cost :   0.019
 1001 epoch  |    0.316  |    0.917  |    0.901  |  cost :   0.018
>>> training time :  7.01240086555481


## Multi-variable linear regression - Predicting exam score

In [5]:
tf.random.set_seed(0)
data = np.array([
    # X1,  X2,  X3,  y
    [ 73., 80., 75., 152. ],
    [ 93.,  88.,  93., 185. ],
    [ 89.,  91.,  90., 180. ],
    [ 96.,  98., 100., 196. ],
    [ 73.,  66.,  70., 142. ]
], np.float32)

X = data[:, :-1]
y = data[:, [-1]]

W = tf.Variable( tf.random.uniform((3,1)) )
b = tf.Variable( tf.random.uniform((1,)) )

learning_rate = 0.000001

def predict(X):
    return tf.matmul( X, W ) + b

print('epoch | cost')
for i in range(2000+1):
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean(tf.square(tf.subtract(predict(X), y)))
    
    if i%200==0:
        print(f'{i+1:5} | {cost:7.3f}')
    
    # calcuating the gradients of the cost
    W_grad, b_grad = tape.gradient( cost, [W, b] )
    
    # updating the variables/parameters (W, b)
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)

epoch | cost
    1 | 6876.448
  201 |   1.048
  401 |   1.041
  601 |   1.035
  801 |   1.029
 1001 |   1.023
 1201 |   1.016
 1401 |   1.010
 1601 |   1.004
 1801 |   0.998
 2001 |   0.993


In [6]:
# weights
print(W.numpy())
print()
print(b.numpy())

[[0.6215449 ]
 [0.52012724]
 [0.8603387 ]]

[0.5595095]


## predict

In [7]:
print(y)  # labels
print()
print(predict(X).numpy())  # prediction

[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]

[[152.06787]
 [184.14587]
 [180.63907]
 [197.23416]
 [140.48439]]


In [8]:
predict([
    [89., 95., 92.],
    [84., 92., 85.]
]).numpy()

array([[184.44025],
       [173.74979]], dtype=float32)