In [1]:
# !pip install tensorflow --upgrade

import numpy as np
import tensorflow as tf
from tensorflow import keras

tf.__version__

'2.1.0'

## Preparing dataset

In [0]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

## One cell: 4 (input_dim) in 2 (hidden_size)

In [3]:
tf.random.set_seed(777)
x_data = np.array([[h]], dtype=np.float32)  # size = [1, 1, 4]

hidden_size = 2
cell = keras.layers.SimpleRNNCell(units=hidden_size)
rnn = keras.layers.RNN(cell=cell, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print(f'x_data: {x_data}, shape: {x_data.shape}')
print(f'outputs: {outputs}, shape: {outputs.shape}')
print(f'states: {states}, shape: {states.shape}')

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[ 0.3680019  -0.56734836]]], shape: (1, 1, 2)
states: [[ 0.3680019  -0.56734836]], shape: (1, 2)


In [4]:
# equivalent to above code
tf.random.set_seed(777)
x_data = np.array([[h]], dtype=np.float32)  # size = [1, 1, 4]

hidden_size = 2
rnn = keras.layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print(f'x_data: {x_data}, shape: {x_data.shape}')
print(f'outputs: {outputs}, shape: {outputs.shape}')
print(f'states: {states}, shape: {states.shape}')

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[ 0.3680019  -0.56734836]]], shape: (1, 1, 2)
states: [[ 0.3680019  -0.56734836]], shape: (1, 2)


## Unfolding to n sequences

In [5]:
tf.random.set_seed(777)
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

hidden_size = 2
rnn = keras.layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print(f'x_data: {x_data}\nshape: {x_data.shape}\n')
print(f'outputs: {outputs}\nshape: {outputs.shape}\n')
print(f'states: {states}\nshape: {states.shape}\n')

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]
shape: (1, 5, 4)

outputs: [[[ 0.3680019  -0.56734836]
  [ 0.4114883   0.13965061]
  [-0.68320704  0.8255957 ]
  [ 0.41370615  0.88117987]
  [ 0.7123188   0.53322625]]]
shape: (1, 5, 2)

states: [[0.7123188  0.53322625]]
shape: (1, 2)



## Batching input

In [6]:
tf.random.set_seed(777)
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
rnn = keras.layers.SimpleRNN(units=2, return_sequences=True, return_state=True)
outputs, state = rnn(x_data)

print(f'x_data: {x_data}\nshape: {x_data.shape}\n')
print(f'outputs: {outputs}\nshape: {outputs.shape}\n')
print(f'state: {state}\nshape: {state.shape}\n')

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]]
shape: (3, 5, 4)

outputs: [[[ 0.3680019  -0.56734836]
  [ 0.4114883   0.13965058]
  [-0.68320704  0.8255957 ]
  [ 0.41370615  0.88117987]
  [ 0.7123188   0.53322625]]

 [[ 0.7602807   0.47803095]
  [ 0.3934883   0.3432451 ]
  [-0.6288044   0.875172  ]
  [ 0.38779333  0.89526427]
  [-0.47752312  0.9527917 ]]

 [[-0.47007686  0.70922625]
  [ 0.19591257  0.87559617]
  [ 0.8198806   0.8860781 ]
  [ 0.5266876   0.92959416]
  [-0.5610914   0.9600702 ]]]
shape: (3, 5, 2)

state: [[ 0.7123188   0.53322625]
 [-0.47752312  0.9527917 ]
 [-0.5610914   0.9600702 ]]
shape: (3, 2)

