In [1]:
import numpy as np
from scipy import sparse

### 1. sparse.coo_matrix( ) - COO format

In [2]:
data = np.array([3,1,2])

row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])

sparse_coo = sparse.coo_matrix((data, (row_pos, col_pos)))
print(sparse_coo)
sparse_coo

  (0, 0)	3
  (0, 2)	1
  (1, 1)	2


<2x3 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

In [3]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

### 2. sparse.csr_matrix( ) - CSR format
#### (CSR is preferred to COO due to efficiency)

In [4]:
data2 = np.array([1, 5, 1, 4, 3, 2, 5, 6, 3, 2, 7, 8, 1])  # elements that are not zero
col_pos = np.array([2, 5, 0, 1, 3, 4, 5, 1, 3, 0, 3, 5, 0])  # column position

# COO format
row_pos = np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
sparse_coo = sparse.coo_matrix( (data2, (row_pos, col_pos)) )
print(sparse_coo.toarray())

print()

# CSR foramt
row_pos_ind = np.array([0, 2, 7, 9, 10, 12, 13])
sparse_csr = sparse.csr_matrix( (data2, col_pos, row_pos_ind) )
print(sparse_csr.toarray())

# check whether two arrays are identical
compare_mat = sparse_coo.toarray() == sparse_csr.toarray()
compare_mat.all()

[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]

[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


True

#### converting dense matrix into sparse matrix

In [5]:
ex_mat = np.array([[0,0,1,0,0,5],
             [1,4,0,3,2,5],
             [0,6,0,3,0,0],
             [2,0,0,0,0,0],
             [0,0,0,7,0,8],
             [1,0,0,0,0,0]])

ex_mat_scr = sparse.csr_matrix(ex_mat)

print(ex_mat_scr)
ex_mat_scr

  (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1


<6x6 sparse matrix of type '<class 'numpy.int32'>'
	with 13 stored elements in Compressed Sparse Row format>