## ref : (edwith) 인공지능을 위한 선형대수https://www.edwith.org/linearalgebra4ai/lecture/19969/

In [1]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import solve

In [2]:
# generating column vector
c = np.array([1,2,3])
print(c.shape)
print(c[0])

(3,)
1


In [3]:
# generating row vector
r = np.array([
    [1,2,3]
])
print(r.shape)

(1, 3)


In [4]:
# obtaining a particular entry
print(r[0,1])

2


In [5]:
# generating a matrix with all zeros
print(np.zeros([2,2]))
print()
# generating a matrix with all ones
print(np.ones([2,2]))
print()
# generating a matrix filled with all the same constant
print(np.full((2,2),7))
print()
# generating a matrix with random values
print(np.random.random((2,2)))  # between [0,1)
print()
print( (4-2) * np.random.random((3,2)) + 2 )  # between [2,4)

[[0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]]

[[7 7]
 [7 7]]

[[0.61916902 0.25996764]
 [0.46746222 0.83335874]]

[[3.4557922  3.3912634 ]
 [2.93970894 2.57166312]
 [2.13389584 3.23537322]]


In [6]:
# generating a matrix
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
# generating another matrix
B = np.array([
    [11,12,13,14],
    [15,16,17,18]
])
B

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [8]:
# transpose a matrix
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [9]:
# matrix-matrix multiplication
np.dot(A, B)
A.dot(B)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [10]:
# Not run - dimension not match
np.dot(B, A)

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [11]:
# coefficient matrix A and a vector b
A = np.array([
    [60, 5.5, 1],
    [65, 5.0, 0],
    [55, 6.0, 1]
])
b = np.array([66, 70, 78])

In [12]:
# identity matrix
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
(np.dot(A, eye3) == A).all()

True

In [14]:
# computing an inverse - numpy.linalg.inv
# np.linalg.inv(A)
A_inv = inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [15]:
# wrong matrix multiplication
A*A_inv

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [16]:
# wrong matrix multiplication
np.dot(A, A_inv)
np.dot(A, A_inv).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [17]:
# solution of a linear system
print(np.dot(A_inv, b))

[ -0.43478261  19.65217391 -16.        ]


In [18]:
# a better way to solve the same linear system - numpy.linalg.solve
# np.linalg.solve(A, b)
solve(A, b)

array([ -0.43478261,  19.65217391, -16.        ])