In [1]:
import keras
from keras.datasets import mnist
from keras.utils import to_categorical

print(keras.__version__)

Using TensorFlow backend.


2.3.1


## Load dataset

In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

print('>>> train dataset info')
print(f'shape of images array : {train_images.shape}')
print(f'shape of labels array : {train_labels.shape}')
print(f'train_labels : {train_labels}')

print('\n>>> test dataset info')
print(f'shape of images array : {test_images.shape}')
print(f'shape of labels array : {test_labels.shape}')
print(f'test_labels : {test_labels}')

11493376/11490434 [==============================] - 30s 3us/step
>>> train dataset info
shape of images array : (60000, 28, 28)
shape of labels array : (60000,)
train_labels : [5 0 4 ... 5 6 8]

>>> test dataset info
shape of images array : (10000, 28, 28)
shape of labels array : (10000,)
test_labels : [7 2 1 ... 4 5 6]


## Preprocess the data

In [4]:
train_images = train_images.reshape((60000, 28*28)).astype('float32') / 255
test_images = test_images.reshape((10000, 28*28)).astype('float32') / 255

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

print('>>> train dataset info')
print(f'shape of images array : {train_images.shape}')
print(f'shape of labels array : {train_labels.shape}')
print(f'train_labels : {train_labels}')

print('\n>>> test dataset info')
print(f'shape of images array : {test_images.shape}')
print(f'shape of labels array : {test_labels.shape}')
print(f'test_labels : {test_labels}')

>>> train dataset info
shape of images array : (60000, 784)
shape of labels array : (60000, 10)
train_labels : [[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]

>>> test dataset info
shape of images array : (10000, 784)
shape of labels array : (10000, 10)
test_labels : [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Generate a neural network model

In [5]:
network = keras.models.Sequential()
network.add( keras.layers.Dense(units=512, activation='relu', input_shape=(28*28, )) )
network.add( keras.layers.Dense(units=10, activation='softmax') )

network.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_2 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


## Compile & Train the model

In [6]:
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

network.fit(x=train_images, y=train_labels, batch_size=120, epochs=5)

Epoch 1/5
60000/60000 [==============================] - 3s 51us/step - loss: 1.4273 - accuracy: 0.6764
Epoch 2/5
60000/60000 [==============================] - 3s 47us/step - loss: 0.5591 - accuracy: 0.8576
Epoch 3/5
60000/60000 [==============================] - 3s 47us/step - loss: 0.3979 - accuracy: 0.8909
Epoch 4/5
60000/60000 [==============================] - 3s 47us/step - loss: 0.3443 - accuracy: 0.9023
Epoch 5/5
60000/60000 [==============================] - 3s 48us/step - loss: 0.3160 - accuracy: 0.9101 0s - loss: 0.3153 - ac


## Evaluate the model

In [7]:
network.evaluate(x=test_images, y=test_labels)

10000/10000 [==============================] - 0s 43us/step


[48.78062454124673, 0.833299994468689]