In [1]:
import tensorflow as tf
from tensorflow import keras

print(tf.__version__)
print(keras.__version__)

1.6.0
2.1.3-tf


## tf.constant, tf.rank, Type

In [2]:
node1 = tf.constant([[4,1]], dtype=tf.float32)
print(node1)
print(tf.rank(node1))
print()

sess = tf.Session()
print(f'values : {sess.run(node1)}')
print(f'rank   : {sess.run(tf.rank(node1))}')
print(f'type   : {type(sess.run(node1))}')
sess.close()

Tensor("Const:0", shape=(1, 2), dtype=float32)
Tensor("Rank:0", shape=(), dtype=int32)

values : [[4. 1.]]
rank   : 2
type   : <class 'numpy.ndarray'>


## tf.constant, tf.rank, Type - using as_default(), eval() method

In [3]:
with tf.Session().as_default():
    print(f'values : {node1.eval()}')
    print(f'rank   : {tf.rank(node1).eval()}')
    print(f'type   : {type(node1.eval())}')

values : [[4. 1.]]
rank   : 2
type   : <class 'numpy.ndarray'>


## tf.placeholder, Feeding

In [4]:
input_data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
y = x * 2

with tf.Session() as sess:
    result = sess.run(y, feed_dict={x:input_data})

print(result)

[ 2.  4.  6.  8. 10.]


## tf.Variable

In [5]:
input_data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
W = tf.Variable(2., dtype=tf.float32)
y = W * x


with tf.Session() as sess:
    init = tf.global_variables_initializer()  # 그래프를 실행하기 전에 변수를 초기화를 해야, 값이 변수에 지정됨
    sess.run(init)
    result = sess.run(y, feed_dict={x:input_data})

print(result)

[ 2.  4.  6.  8. 10.]


## Matrix calculation - tf.matmul()

In [6]:
x = tf.constant([[1, 2, 3]], dtype=tf.float32)
w = tf.constant([[2], [2], [2]], dtype=tf.float32)
y = tf.matmul(x, w)

print(f'shape of x : {x.get_shape()}')
print(f'shape of w : {w.get_shape()}')
print(f'shape of y : {y.get_shape()}')


with tf.Session() as sess:
    result = sess.run(y)
print(f'\nmatmul result = {result}')

shape of x : (1, 3)
shape of w : (3, 1)
shape of y : (1, 1)

matmul result = [[12.]]


## Matrix calculation - using tf.placeholder

In [7]:
input_data = [[1,2,3], [1,2,3], [2,3,4]]
x = tf.placeholder(dtype=tf.float32, shape=[None, 3])
w = tf.constant([[2], [2], [2]], dtype=tf.float32)
y = tf.matmul(x, w)

print(f'shape of x : {x.get_shape()}')
print(f'shape of w : {w.get_shape()}')
print(f'shape of y : {y.get_shape()}')


with tf.Session() as sess:
    result = sess.run(y, feed_dict={x:input_data})
print(f'\nmatmul result = \n{result}')

shape of x : (?, 3)
shape of w : (3, 1)
shape of y : (?, 1)

matmul result = 
[[12.]
 [12.]
 [18.]]
